### ISSUE TITLE
extension id

### ISSUE THREAD

**Issue by blade-runner** [AktivCo/rutokenweb-plugin-js#1]
Extension id in chrome webstore is jckbgpagkmmelgnignecpjbibajiacei

https://chrome.google.com/webstore/detail/%D0%B0%D0%B4%D0%B0%D0%BF%D1%82%D0%B5%D1%80-%D1%80%D1%83%D1%82%D0%BE%D0%BA%D0%B5%D0%BD-web-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8/jckbgpagkmmelgnignecpjbibajiacei

**Comment by villytiger** [comment]
Cannot reproduce.
