### ISSUE TITLE
Invalid port. Linux

### ISSUE THREAD

**Issue by zolateater** [AktivCo/rutokenweb-plugin-js#2]
Расширение для Google Chrome Linux версии работает через раз - большая часть попыток выполнить js (даже из примера) дает лишь сообщение, выводимое в консоль - Invalid port.
В то же время, под в Google Chrome под Windows тот же самый код выполняется.
Подскажите, под Linux расширение вообще работоспособно, или же оно предназначено только для Windows-версии?

**Comment by villytiger** [comment]
Google Chrome версии 45 и выше на данный момент поддерживается только плагином версии 1.6.1.0, которая пока выпущена только для Windows. Поэтому наблюдаемое поведение вполне ожидаемо.

**Comment by uzbxodgiev** [comment]
Добрый день, можете сказать когда решиться это. Так как до сих пор это ошибка есть в linux е по рутокену.

**Comment by mescheryakov1** [comment]
https://github.com/AktivCo/rutokenweb-to-plugin
