### ISSUE TITLE
Код ошибки -22 при создании подписи

### ISSUE THREAD

**Issue by zolateater** [AktivCo/rutokenweb-plugin-js#3]
Здравствуйте! Успешно интегрировали Рутокен WEB в свой продукт, однако столкнулись с проблемой - после форматирования токена метод создания публичного ключа возвращает ошибку  -22 - контейнер не найден. Однако, утилита для администрирования показывает, что контейнер создается. Воспроизводится в браузерах использующий и новый, и старый  интерфейс плагина.

**Comment by blade-runner** [comment]
Напишите, чем форматируете токен, какой тулзой?
Какой метод вызываете потом (название)?
Вероятно после форматирования не создается контейнер с ключом восстановления. 
-22 - Контейнер учетной записи поврежден

**Comment by zolateater** [comment]
Прислали с саппорта новую версию утилиты форматирования - токены отформатированные ей работают. Действительно, по всей видимости, не создавался контейнер с ключом восстановления.
