### ISSUE TITLE
Invalid port: FireWyrmPort1 Linux

### ISSUE THREAD

**Issue by uzbxodgiev** [AktivCo/rutokenweb-plugin-js#4]
Расширение для Google Chrome Linux версии работает через раз - большая часть попыток выполнить js (даже из примера) дает лишь сообщение, выводимое в консоль - Invalid port.
В то же время, под в Google Chrome под Windows тот же самый код выполняется.
Подскажите, под Linux расширение вообще работоспособно, или же оно предназначено только для Windows-версии? Я повтораю закрытую тему которая до сих пор не решена.

**Comment by mescheryakov1** [comment]
Добрый день.

развитие плагина Рутокен Web остановлено и версия работающая с native messaging под linux выпускаться же не будет. 
Мы концентрируемся на развитии и поддержке более удобного и полнофункционального продукта "Рутокен Плагин" полностью заменяющего продукт "плагин Рутокен Web"
Для получения помощи при переходе с "плагина Рутокен Web" на "Рутокен Плагин" пожалуйста свяжитесь с нами по почте info@rutoken.ru

**Comment by mescheryakov1** [comment]
https://github.com/AktivCo/rutokenweb-to-plugin
